# Generated by Django 4.2.5 on 2023-10-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
